### TOKENIZE
POST {{url-base}}/{{realm}}{{url-token}}
Content-Type: application/x-www-form-urlencoded

client_id={{client-id}}
&grant_type=password
&username=admin
&password={{password}}
&client_secret={{client-secret}}

### LOGIN
POST {{base-url-api}}{{login-endpoint}}
Content-Type: application/json

{
  "username": "user1",
  "password": "{{password}}"
}

### FIND ALL USERS
GET {{base-url-api}}{{users-endpoint}}
Authorization: Bearer {{admin-token}}

### FIND ALL PRODUCTS | ADMIN
GET http://localhost:8090/products
Authorization: Bearer {{admin-token}}

### FIND ALL PRODUCTS | USER1
GET {{base-url-api}}{{products-endpoint}}
Authorization: Bearer {{user-token}}
