### TOKENIZE
POST {{url-base}}/{{realm}}{{url-token}}
Content-Type: application/x-www-form-urlencoded

client_id={{client-id}}
&grant_type=password
&username=admin
&password={{password}}
&client_secret={{client-secret}}

### LOGIN
POST http://localhost:8090/keycloak/users/login
Content-Type: application/json

{
  "username": "admin",
  "password": {{password}}
}

###

### FIND ALL USERS
GET http://localhost:8090/keycloak/users
Authorization: Bearer {{user-token}}