POST http://localhost:8181/realms/microservices-realm/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=auth-server
&grant_type=password
&username=admin
&password={{password}}
&client_secret=LeT1TRw3rFKZtxlUFM2JBfmi5QFjTIm2

###
GET http://localhost:8090/test/admin
Authorization: bearer {{token_user}}

###
GET http://localhost:8090/test/user
Authorization: bearer {{token_user}}

###
GET http://localhost:8090/keycloak/users
Authorization: bearer {{token_admin}}