spring:
  application:
    name: keycloak-auth
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  main:
    allow-bean-definition-overriding: true

  liquibase:
    change-log: classpath:database/liquibase-changelog.yml
    url: jdbc:postgresql://localhost:${DB_PORT}/${DB_NAME}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    enabled: false

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database: postgresql
    open-in-view: false
    generate-ddl: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEY_SERVER}:8181/realms/${KEY_REALM_NAME}
          jwk-set-uri: ${KEY_SERVER}:8181/realms/${KEY_REALM_NAME}/protocol/openid-connect/certs

server:
  port: 8090

app:
  name: '@project.name@'
  description: '@project.description@'
  version: '@project.version@'

# Keycloak config
keycloak:
  server: ${KEY_SERVER}:${KEYCLOAK_PORT}
  realm-name: ${KEY_REALM_NAME}
  realm-master: ${KEY_REALM_MASTER}
  admin-cli: ${KEY_ADMIN_CLI}
  user-console: ${KEY_USER_CONSOLE}
  pass-console: ${KEY_PASS_CONSOLE}
  client-secret: ${KEY_CLIENT_SECRET}
  client-id: ${KEY_CLIENT_ID}
  url-login: ${KEY_SERVER}:${KEYCLOAK_PORT}/realms/${KEY_REALM_NAME}/protocol/openid-connect/token
  port: ${KEYCLOAK_PORT}


api.security:
  mapping: /**
  allowed-origins:
    - "*"
  allowed-methods:
    - GET
    - POST
    - PATCH
    - PUT
    - DELETE
    - POTIONS
    - HEAD
  allowed-head:
    - "*"
  endpoints:
    - path: /test/admin
      authorities: [ADMIN]
    - path: /test/user
      authorities: [ADMIN, USER]


