spring:
  application:
    name: keycloak-auth
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  main:
    allow-bean-definition-overriding: true

  liquibase:
    change-log: classpath:database/liquibase-changelog.yml
    url: jdbc:postgresql://localhost:${DB_PORT}/${DB_NAME}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    enabled: false

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database: postgresql
    open-in-view: false
    generate-ddl: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${HOST_AUTH_SERVER}:8181/realms/${REALM_NAME}
          jwk-set-uri: ${HOST_AUTH_SERVER}:8181/realms/${REALM_NAME}/protocol/openid-connect/certs

server:
  port: 8090

app:
  name: 'Keycloak Auth'
  description: 'Una descripción'
  version: '1.0.0'

# Keycloak config
keycloak:
  server: ${KC_SERVER}
  realm-name: ${KC_REALM_NAME}
  realm-master: ${KC_REALM_MASTER}
  admin-cli: ${KC_ADMIN_CLI}
  user-console: ${KC_USER_CONSOLE}
  pass-console: ${KC_PASS_CONSOLE}
  client-secret: ${KC_CLIENT_SECRET}

api.security:
  origins:
    - "*"
  endpoints:
    - path: /test/admin
      authorities: [ADMIN]
    - path: /test/user
      authorities: [ADMIN, USER]

